version: '3.8'

services:
  db:
    image: postgres:13
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: treasure_chest_db
      POSTGRES_USER: wzq
      POSTGRES_PASSWORD: '123456'
    ports:
      - '5432:5432'
    volumes:
      # Mount a volume for persistent data
      - postgres-data:/var/lib/postgresql/data

# Define a top-level volume for data if you prefer that over a bind mount
volumes:
 postgres-data:
